### ISSUE TITLE
Allow PHP 8 usage

### ISSUE THREAD

**Issue by the-toster** [zakirullin/mess#11]
Hi, it would be great to have ability to use this lib with php8, just more loose version constraint (`^7.2` =>`'^7.2|^8.0`). Is PR acceptable?

**Comment by zakirullin** [comment]
Hi! Yes, for sure!

**Comment by zakirullin** [comment]
I am on vacation, so I can only review/merge/tag PRs. If you made one, I'd gladly accept it :)

**Comment by the-toster** [comment]
^^^ Here it is)
