### ISSUE TITLE
MessInterface should have psalm annotations

### ISSUE THREAD

**Issue by the-toster** [zakirullin/mess#7]
Thank you for this lib. It's very useful with psalm.

When I use something like `(new Mess($options))['key']->getArrayOfStringToString()` psalm infer it type as `array<array-key, mixed>`, because `Mess::getOffset()` returns `MessInterface`, where `getArrayOfStringToString` are not annotated.

So I suggest annotate it too.

If you think this is ok, I will crete PR.

**Comment by zakirullin** [comment]
Yeah, that would be great! Wonder why I didn't add this myself.

**Comment by zakirullin** [comment]
Yeah, that would be great! Wonder why I didn't come across this myself.
